// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * @file GitHub Pages compatibility landing contracts.
 * @input The one-page source, static Astryx assets, and direct Pages workflow.
 * @output Product copy, route recovery, accessibility, and ownership checks.
 * @position Prevents the legacy origin from becoming a second maintained site.
 */

import {createHash} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import {JSDOM} from 'jsdom';
import {describe, expect, it} from 'vitest';
import yaml from 'yaml';

const ROOT = path.resolve(import.meta.dirname, '../..');
const PAGE_PATH = path.join(ROOT, '.github/pages/index.html');
const ASSET_ROOT = path.join(ROOT, '.github/pages/assets');
const PAGE = fs.readFileSync(PAGE_PATH, 'utf8');
const CORE_CSS = fs.readFileSync(path.join(ASSET_ROOT, 'astryx.css'), 'utf8');
const THEME = fs.readFileSync(path.join(ASSET_ROOT, 'theme.css'), 'utf8');
const ASSET_MANIFEST = JSON.parse(
  fs.readFileSync(path.join(ASSET_ROOT, 'manifest.json'), 'utf8'),
);

function render(url) {
  return new JSDOM(PAGE, {runScripts: 'dangerously', url}).window.document;
}

function luminance(hex) {
  const channels = hex
    .match(/[0-9a-f]{2}/gi)
    .map(channel => Number.parseInt(channel, 16) / 255)
    .map(channel =>
      channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4,
    );
  return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2];
}

function contrast(foreground, background) {
  const values = [luminance(foreground), luminance(background)].sort(
    (a, b) => b - a,
  );
  return (values[0] + 0.05) / (values[1] + 0.05);
}

function themePair(token) {
  const match = THEME.match(
    new RegExp(
      `--${token}:\\s*light-dark\\((#[0-9a-f]+),\\s*(#[0-9a-f]+)\\)`,
      'i',
    ),
  );
  expect(match, `Expected ${token} in the neutral theme`).not.toBeNull();
  return {light: match[1], dark: match[2]};
}

describe('GitHub Pages compatibility landing', () => {
  it('uses the public Astryx static style layers on root and recovery paths', () => {
    const document = render(
      'https://facebook.github.io/astryx/storybook/?path=/story/core-button--primary',
    );
    expect(document.documentElement.dataset.astryxTheme).toBe('neutral');
    expect(
      [...document.querySelectorAll('link[rel="stylesheet"]')].map(
        link => link.href,
      ),
    ).toEqual([
      'https://facebook.github.io/astryx/assets/reset.css',
      'https://facebook.github.io/astryx/assets/astryx.css',
      'https://facebook.github.io/astryx/assets/theme.css',
    ]);

    const copyright = 'Copyright (c) Meta Platforms, Inc. and affiliates.';
    const assets = {
      'reset.css': [copyright, 'Astryx Reset Stylesheet', '@layer reset'],
      'astryx.css': [
        copyright,
        'Astryx Pre-compiled StyleX CSS',
        '@layer astryx-base',
      ],
      'theme.css': [
        copyright,
        '@generated by `astryx theme build`',
        '[data-astryx-theme="neutral"]',
      ],
    };
    for (const [file, markers] of Object.entries(assets)) {
      const contents = fs.readFileSync(path.join(ASSET_ROOT, file), 'utf8');
      for (const marker of markers) {
        expect(contents).toContain(marker);
      }
    }
  });

  it('pins the generated assets to the current public package releases', () => {
    const packageVersions = Object.fromEntries(
      [
        ['@astryxdesign/core', 'packages/core/package.json'],
        ['@astryxdesign/theme-neutral', 'packages/themes/neutral/package.json'],
      ].map(([name, filename]) => [
        name,
        JSON.parse(fs.readFileSync(path.join(ROOT, filename), 'utf8')).version,
      ]),
    );
    expect(ASSET_MANIFEST.schemaVersion).toBe(1);
    expect(ASSET_MANIFEST.sources).toEqual(packageVersions);

    for (const [filename, expected] of Object.entries(ASSET_MANIFEST.files)) {
      const contents = fs.readFileSync(path.join(ASSET_ROOT, filename));
      expect(createHash('sha256').update(contents).digest('hex')).toBe(
        expected.sha256,
      );
    }

    expect(fs.readFileSync(path.join(ASSET_ROOT, 'reset.css'), 'utf8')).toBe(
      fs.readFileSync(path.join(ROOT, 'packages/core/src/reset.css'), 'utf8'),
    );
    expect(THEME).toContain(
      `Core: @astryxdesign/core@${packageVersions['@astryxdesign/core']}`,
    );
  });

  it('keeps text and shipped focus tokens above WCAG contrast requirements in both modes', () => {
    const focusTokens = CORE_CSS.match(
      /--focus-outline-width:([^;]+);--focus-outline-style:([^;]+);--focus-outline-color:([^;]+);--focus-outline-offset:([^;}]+)/,
    );
    expect(focusTokens).not.toBeNull();
    expect(focusTokens.slice(1)).toEqual([
      '2px',
      'solid',
      'var(--color-accent)',
      '3px',
    ]);
    expect(PAGE).toContain('outline: var(--focus-outline-width)');
    expect(PAGE).toContain('var(--focus-outline-color)');
    expect(PAGE).toContain('outline-offset: var(--focus-outline-offset)');

    const body = themePair('color-background-body');
    const card = themePair('color-background-card');
    const primary = themePair('color-text-primary');
    const secondary = themePair('color-text-secondary');
    const accent = themePair('color-accent');

    for (const mode of ['light', 'dark']) {
      expect(contrast(primary[mode], body[mode])).toBeGreaterThanOrEqual(4.5);
      expect(contrast(secondary[mode], body[mode])).toBeGreaterThanOrEqual(4.5);
      expect(contrast(primary[mode], card[mode])).toBeGreaterThanOrEqual(4.5);
      expect(contrast(secondary[mode], card[mode])).toBeGreaterThanOrEqual(4.5);
      expect(contrast(accent[mode], body[mode])).toBeGreaterThanOrEqual(3);
      expect(contrast(accent[mode], card[mode])).toBeGreaterThanOrEqual(3);
    }
  });

  it('presents the current public Astryx destinations in semantic order', () => {
    const document = render('https://facebook.github.io/astryx/');
    expect(document.title).toBe('Astryx Design System');
    expect(document.querySelector('main h1')?.textContent).toBe(
      'Astryx Design System',
    );
    expect(document.querySelector('nav')?.getAttribute('aria-label')).toBe(
      'Astryx destinations',
    );
    expect(
      [...document.querySelectorAll('nav > a')].map(link => [
        link.id,
        link.href,
      ]),
    ).toEqual([
      ['documentation', 'https://astryx.atmeta.com/'],
      ['storybook', 'https://astryx.atmeta.com/storybook/'],
      ['sandbox', 'https://astryx.atmeta.com/sandbox/'],
      ['repository', 'https://github.com/facebook/astryx'],
    ]);
    expect(document.querySelector('#documentation')?.classList).toContain(
      'primary',
    );
    expect(
      document.querySelectorAll('.arrow[aria-hidden="true"]'),
    ).toHaveLength(4);
  });

  it('keeps the compatibility origin noindex with the docsite canonical', () => {
    const document = render('https://facebook.github.io/astryx/');
    expect(document.querySelector('link[rel="canonical"]')?.href).toBe(
      'https://astryx.atmeta.com/',
    );
    expect(document.querySelector('meta[name="robots"]')?.content).toBe(
      'noindex, follow',
    );
    expect(PAGE).not.toMatch(/internalfb|localhost|@xds|@nest/i);
  });

  it.each([
    [
      'Storybook',
      'https://facebook.github.io/astryx/storybook/?path=/story/core-button--primary#docs',
      '#storybook',
      'https://astryx.atmeta.com/storybook/?path=/story/core-button--primary#docs',
    ],
    [
      'Sandbox',
      'https://facebook.github.io/astryx/sandbox/templates/login-sso/?theme=dark#preview',
      '#sandbox',
      'https://astryx.atmeta.com/sandbox/templates/login-sso/?theme=dark#preview',
    ],
  ])(
    'preserves an old %s deep link in its recovery destination',
    (_name, oldUrl, selector, expected) => {
      expect(render(oldUrl).querySelector(selector)?.href).toBe(expected);
    },
  );

  it('does not guess a destination for unrelated old paths', () => {
    const document = render(
      'https://facebook.github.io/astryx/reports/old-run/?view=details#failure',
    );
    expect(document.querySelector('#storybook')?.href).toBe(
      'https://astryx.atmeta.com/storybook/',
    );
    expect(document.querySelector('#sandbox')?.href).toBe(
      'https://astryx.atmeta.com/sandbox/',
    );
  });

  it('publishes the whole static page as index and 404 without app builds', () => {
    const workflow = yaml.parse(
      fs.readFileSync(
        path.join(ROOT, '.github/workflows/pages-deploy.yml'),
        'utf8',
      ),
    );
    expect(workflow.on.workflow_run).toBeUndefined();
    expect(workflow.on.push.branches).toEqual(['main']);
    expect(workflow.concurrency).toEqual({
      group: 'github-pages-landing',
      'cancel-in-progress': true,
    });
    expect(Object.keys(workflow.jobs)).toEqual(['deploy']);
    const command = workflow.jobs.deploy.steps
      .map(step => step.run ?? '')
      .join('\n');
    expect(command).toContain('cp -R .github/pages/. pages-dist/');
    expect(command).toContain(
      'cp .github/pages/index.html pages-dist/404.html',
    );
    expect(command).not.toContain('storybook');
    expect(command).not.toContain('sandbox');
    expect(command).not.toContain('gh-pages');
  });
});
