// Copyright (c) Meta Platforms, Inc. and affiliates.

import {describe, it, expect, afterEach, vi} from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import {
  detectPackageManager,
  explainPackageManager,
  getDlxPrefix,
  isCliOneOff,
  cliBinResolves,
  getCliInvocation,
  formatCliCommand,
} from './package-manager.mjs';

let tmpDir;
const ORIGINAL_ARGV1 = process.argv[1];

afterEach(() => {
  if (tmpDir) {
    fs.rmSync(tmpDir, {recursive: true, force: true});
    tmpDir = null;
  }
  vi.restoreAllMocks();
  delete process.env.npm_config_user_agent;
  process.argv[1] = ORIGINAL_ARGV1;
});

function makeTmpDir() {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'astryx-pm-test-'));
  return tmpDir;
}

/** Install the CLI's bin link in `dir`, the way a package manager does. */
function linkCliBin(dir, name = 'astryx') {
  const binDir = path.join(dir, 'node_modules', '.bin');
  fs.mkdirSync(binDir, {recursive: true});
  fs.writeFileSync(path.join(binDir, name), '');
}

/** The header a classic Yarn (1.x) lockfile starts with. */
const YARN_V1_LOCK =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n';

/** The header a Berry (Yarn 2+) lockfile starts with. */
const YARN_BERRY_LOCK =
  '# This file is generated by running "yarn install" inside your project.\n# Manual changes might be lost - proceed with caution!\n\n__metadata:\n  version: 8\n';

/** An installed CLI's entry, outside any runner cache (a global or workspace install). */
const INSTALLED_ENTRY = '/usr/local/lib/node_modules/@astryxdesign/cli/clients/cli/bin/astryx.mjs';

describe('detectPackageManager', () => {
  it('detects yarn from yarn.lock', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    expect(detectPackageManager(dir)).toBe('yarn');
  });

  it('detects pnpm from pnpm-lock.yaml', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    expect(detectPackageManager(dir)).toBe('pnpm');
  });

  it('detects npm from package-lock.json', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'package-lock.json'), '{}');
    expect(detectPackageManager(dir)).toBe('npm');
  });

  it('detects bun from bun.lockb', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'bun.lockb'), '');
    expect(detectPackageManager(dir)).toBe('bun');
  });

  it('refuses to let the runner break a multi-lockfile tie', () => {
    // One `yarn install` inside a pnpm project leaves a yarn.lock next to the
    // committed pnpm-lock.yaml. Nothing the project owns picks between them, so
    // there is no honest answer to give — only the neutral one.
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    process.env.npm_config_user_agent = 'pnpm/11.10.0 npm/? node/v22.0.0';
    expect(detectPackageManager(dir)).toBe('npx');
    expect(explainPackageManager(dir)).toMatchObject({
      ambiguous: true,
      candidates: ['yarn', 'pnpm'],
    });
  });

  it('does not reproduce a wrong `yarn astryx` line it was invoked through', () => {
    // The regression: an agent handed the wrong `yarn astryx` line runs the CLI
    // THROUGH yarn, so npm_config_user_agent says yarn. A runner tiebreak then
    // agrees with the mistake, and regenerating agent docs writes it again —
    // the wrong line reproduces itself forever. Project evidence only.
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    linkCliBin(dir);
    process.env.npm_config_user_agent = 'yarn/1.22.21 npm/? node/v22.0.0';
    expect(detectPackageManager(dir)).not.toBe('yarn');
    expect(getCliInvocation(dir)).toBe('npx astryx');
  });

  it('does not reproduce it for a directly invoked installed binary either', () => {
    const dir = makeTmpDir();
    const entry = process.argv[1];
    try {
      fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
      fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
      linkCliBin(dir);
      process.env.npm_config_user_agent = 'yarn/1.22.21 npm/? node/v22.0.0';
      process.argv[1] = path.join(dir, 'node_modules/.bin/astryx');
      expect(getCliInvocation(dir)).toBe('npx astryx');
    } finally {
      process.argv[1] = entry;
    }
  });

  it('breaks the tie from a committed pnpm-workspace.yaml', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    fs.writeFileSync(path.join(dir, 'pnpm-workspace.yaml'), 'packages: []\n');
    process.env.npm_config_user_agent = 'yarn/1.22.21 npm/? node/v22.0.0';
    expect(detectPackageManager(dir)).toBe('pnpm');
  });

  it('breaks the tie from a committed .yarnrc.yml', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    fs.writeFileSync(path.join(dir, '.yarnrc.yml'), 'nodeLinker: node-modules\n');
    expect(detectPackageManager(dir)).toBe('yarn');
  });

  it('stays ambiguous when the project owns evidence for both', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    fs.writeFileSync(path.join(dir, 'pnpm-workspace.yaml'), 'packages: []\n');
    fs.writeFileSync(path.join(dir, '.yarnrc.yml'), '');
    expect(explainPackageManager(dir).ambiguous).toBe(true);
  });

  it('lets the packageManager field break a multi-lockfile tie', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'pnpm@11.10.0'}),
    );
    expect(detectPackageManager(dir)).toBe('pnpm');
  });

  it('follows the declared packageManager even when no lockfile matches it', () => {
    // The declaration is the project speaking. Two lockfiles that disagree
    // with it are two traces that are both wrong, not a tie to resolve.
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    fs.writeFileSync(path.join(dir, 'package-lock.json'), '{}');
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'pnpm@11.10.0'}),
    );
    expect(explainPackageManager(dir)).toMatchObject({
      pm: 'pnpm',
      ambiguous: false,
      declared: 'pnpm',
      source: 'declared',
    });
  });

  it('ignores a runner that has no lockfile in the directory', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    process.env.npm_config_user_agent = 'yarn/1.22.21 npm/? node/v22.0.0';
    expect(detectPackageManager(dir)).toBe('pnpm');
  });

  it('detects from packageManager field in package.json (no lockfile)', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'yarn@4.1.0'}),
    );
    expect(detectPackageManager(dir)).toBe('yarn');
  });

  it('detects pnpm from packageManager field', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'pnpm@8.0.0'}),
    );
    expect(detectPackageManager(dir)).toBe('pnpm');
  });

  it('ignores unknown packageManager values', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'unknown@1.0.0'}),
    );
    expect(detectPackageManager(dir)).toBe('npx');
  });

  it('declared packageManager outranks a single stray lockfile', () => {
    // The regression: one `yarn install` inside a pnpm project leaves a
    // yarn.lock forever, and a single lockfile used to outrank the field. The
    // CLI then printed `yarn astryx` for a pnpm project — and wrote that line
    // into the agent docs, where agents copy it.
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'pnpm@8.0.0'}),
    );
    linkCliBin(dir);
    expect(detectPackageManager(dir)).toBe('pnpm');
    expect(getCliInvocation(dir)).toBe('pnpm exec astryx');
  });

  it('reports the stray lockfile it ignored, so doctor can name it', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'pnpm@8.0.0'}),
    );
    expect(explainPackageManager(dir)).toMatchObject({
      pm: 'pnpm',
      declared: 'pnpm',
      source: 'declared',
      strayLockfiles: [{pm: 'yarn', file: 'yarn.lock'}],
    });
  });

  it('reports no stray when the lockfile agrees with the declaration', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'pnpm@8.0.0'}),
    );
    expect(explainPackageManager(dir)).toMatchObject({
      pm: 'pnpm',
      declared: 'pnpm',
      strayLockfiles: [],
    });
  });

  it('keeps the lockfile fallback when nothing is declared', () => {
    // The documented fallback: with no declaration, one lockfile still decides.
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({}));
    expect(explainPackageManager(dir)).toMatchObject({
      pm: 'yarn',
      declared: null,
      source: 'lockfile',
    });
  });

  it('ignores an unknown packageManager value and falls back to the lockfile', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'unknown@1.0.0'}),
    );
    expect(detectPackageManager(dir)).toBe('yarn');
  });

  it('lets a nearer directory answer before an outer declaration', () => {
    // Unchanged walk-up behaviour: the first directory that answers wins, so a
    // workspace root's declaration does not reach past a package that has its
    // own lockfile.
    const dir = makeTmpDir();
    const inner = path.join(dir, 'packages', 'app');
    fs.mkdirSync(inner, {recursive: true});
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'pnpm@8.0.0'}),
    );
    fs.writeFileSync(path.join(inner, 'package-lock.json'), '{}');
    expect(detectPackageManager(inner)).toBe('npm');
    expect(detectPackageManager(dir)).toBe('pnpm');
  });

  it('detects from npm_config_user_agent env var', () => {
    const dir = makeTmpDir();
    process.env.npm_config_user_agent = 'yarn/1.22.22 node/v20.0.0';
    expect(detectPackageManager(dir)).toBe('yarn');
  });

  it('detects pnpm from npm_config_user_agent env var', () => {
    const dir = makeTmpDir();
    process.env.npm_config_user_agent = 'pnpm/8.15.0 node/v20.0.0';
    expect(detectPackageManager(dir)).toBe('pnpm');
  });

  it('falls back to npx when no signals present', () => {
    const dir = makeTmpDir();
    expect(detectPackageManager(dir)).toBe('npx');
  });

  it('packageManager field takes priority over npm_config_user_agent', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(
      path.join(dir, 'package.json'),
      JSON.stringify({packageManager: 'bun@1.0.0'}),
    );
    process.env.npm_config_user_agent = 'npm/10.0.0 node/v20.0.0';
    expect(detectPackageManager(dir)).toBe('bun');
  });
});

describe('getDlxPrefix', () => {
  it('returns "pnpm dlx" for pnpm projects', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    expect(getDlxPrefix(dir)).toBe('pnpm dlx');
  });

  it('returns "yarn dlx" for yarn projects', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), '');
    expect(getDlxPrefix(dir)).toBe('yarn dlx');
  });

  // Classic Yarn (1.x) has no `dlx`; `yarn dlx …` fails there, so its one-off
  // form is `npx`. Berry (2+) keeps `yarn dlx`.
  it('returns "npx" for a classic Yarn lockfile', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), YARN_V1_LOCK);
    expect(getDlxPrefix(dir)).toBe('npx');
  });

  it('returns "yarn dlx" for a Berry lockfile', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'yarn.lock'), YARN_BERRY_LOCK);
    expect(getDlxPrefix(dir)).toBe('yarn dlx');
  });

  it('reads the declared packageManager version first', () => {
    const classic = makeTmpDir();
    fs.writeFileSync(
      path.join(classic, 'package.json'),
      JSON.stringify({packageManager: 'yarn@1.22.19'}),
    );
    // A Berry-looking lockfile does not outrank the declaration.
    fs.writeFileSync(path.join(classic, 'yarn.lock'), YARN_BERRY_LOCK);
    expect(getDlxPrefix(classic)).toBe('npx');
    fs.rmSync(classic, {recursive: true, force: true});

    const berry = makeTmpDir();
    fs.writeFileSync(
      path.join(berry, 'package.json'),
      JSON.stringify({packageManager: 'yarn@4.5.0'}),
    );
    fs.writeFileSync(path.join(berry, 'yarn.lock'), YARN_V1_LOCK);
    expect(getDlxPrefix(berry)).toBe('yarn dlx');
  });

  it('reads a bare major version in the declaration', () => {
    const classic = makeTmpDir();
    fs.writeFileSync(
      path.join(classic, 'package.json'),
      JSON.stringify({packageManager: 'yarn@1'}),
    );
    expect(getDlxPrefix(classic)).toBe('npx');
    fs.rmSync(classic, {recursive: true, force: true});

    const berry = makeTmpDir();
    fs.writeFileSync(
      path.join(berry, 'package.json'),
      JSON.stringify({packageManager: 'yarn@4'}),
    );
    expect(getDlxPrefix(berry)).toBe('yarn dlx');
  });

  it('reads a committed Yarn config when the lockfile has no header', () => {
    const classic = makeTmpDir();
    fs.writeFileSync(path.join(classic, 'yarn.lock'), '');
    fs.writeFileSync(path.join(classic, '.yarnrc'), '');
    expect(getDlxPrefix(classic)).toBe('npx');
    fs.rmSync(classic, {recursive: true, force: true});

    const berry = makeTmpDir();
    fs.writeFileSync(path.join(berry, 'yarn.lock'), '');
    fs.writeFileSync(path.join(berry, '.yarnrc.yml'), '');
    expect(getDlxPrefix(berry)).toBe('yarn dlx');
  });

  it('reads the runner version when nothing on disk names Yarn', () => {
    makeTmpDir();
    process.env.npm_config_user_agent = 'yarn/1.22.21 npm/? node/v22.0.0';
    expect(getDlxPrefix(tmpDir)).toBe('npx');
    process.env.npm_config_user_agent = 'yarn/4.5.0 npm/? node/v22.0.0';
    expect(getDlxPrefix(tmpDir)).toBe('yarn dlx');
  });

  it('returns "bunx" for bun projects', () => {
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'bun.lockb'), '');
    expect(getDlxPrefix(dir)).toBe('bunx');
  });

  it('falls back to "npx" with no signals', () => {
    const dir = makeTmpDir();
    delete process.env.npm_config_user_agent;
    expect(getDlxPrefix(dir)).toBe('npx');
  });
});

describe('isCliOneOff', () => {
  it('detects an npm npx cache entry', () => {
    process.argv[1] = '/home/u/.npm/_npx/a1b2/node_modules/.bin/astryx';
    expect(isCliOneOff()).toBe(true);
  });

  it('detects a pnpm dlx cache entry', () => {
    process.argv[1] = '/home/u/.cache/pnpm/dlx/9f/node_modules/@astryxdesign/cli/bin/astryx.mjs';
    expect(isCliOneOff()).toBe(true);
  });

  it('detects a bunx cache entry', () => {
    process.argv[1] = '/home/u/.bun/install/cache/@astryxdesign/cli/bin/astryx.mjs';
    expect(isCliOneOff()).toBe(true);
  });

  it('is false for an installed node_modules entry', () => {
    process.argv[1] = '/proj/node_modules/@astryxdesign/cli/bin/astryx.mjs';
    expect(isCliOneOff()).toBe(false);
  });

  it('is false for a source checkout (dev) entry', () => {
    process.argv[1] = '/repo/packages/cli/bin/astryx.mjs';
    expect(isCliOneOff()).toBe(false);
  });
});

describe('cliBinResolves', () => {
  it('finds the bin link in the project', () => {
    const dir = makeTmpDir();
    linkCliBin(dir);
    expect(cliBinResolves(dir)).toBe(true);
  });

  it('finds it in a folder above the project (a workspace root)', () => {
    const root = makeTmpDir();
    linkCliBin(root);
    const pkg = path.join(root, 'packages', 'app');
    fs.mkdirSync(pkg, {recursive: true});
    expect(cliBinResolves(pkg)).toBe(true);
  });

  it('finds a Windows shim', () => {
    const dir = makeTmpDir();
    linkCliBin(dir, 'astryx.cmd');
    expect(cliBinResolves(dir)).toBe(true);
  });

  it('is false when no bin link exists up the tree', () => {
    const dir = makeTmpDir();
    fs.mkdirSync(path.join(dir, 'node_modules', '.bin'), {recursive: true});
    expect(cliBinResolves(dir)).toBe(false);
  });
});

describe('getCliInvocation', () => {
  it('uses the run-prefix + bare bin when the bin resolves from the project', () => {
    process.argv[1] = '/proj/node_modules/@astryxdesign/cli/bin/astryx.mjs';
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    linkCliBin(dir);
    expect(getCliInvocation(dir)).toBe('pnpm exec astryx');
  });

  it('keeps `npx astryx` for a project with a local CLI', () => {
    process.argv[1] = INSTALLED_ENTRY;
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'package-lock.json'), '{}');
    linkCliBin(dir);
    expect(getCliInvocation(dir)).toBe('npx astryx');
  });

  it('keeps the installed form in a workspace package when the root has the bin', () => {
    process.argv[1] = INSTALLED_ENTRY;
    const root = makeTmpDir();
    fs.writeFileSync(path.join(root, 'pnpm-lock.yaml'), '');
    linkCliBin(root);
    const pkg = path.join(root, 'packages', 'app');
    fs.mkdirSync(pkg, {recursive: true});
    fs.writeFileSync(path.join(pkg, 'package.json'), '{"name":"app"}');
    expect(getCliInvocation(pkg)).toBe('pnpm exec astryx');
  });

  // The hazard: the npm package named `astryx` is not this CLI. Launched from
  // an installed path (a global install, or a workspace install running in a
  // fresh package), the CLI used to print `npx astryx` for a project where that
  // bin does not resolve, so following the hint fetched someone else's package.
  it.each([
    ['package-lock.json', '{}', 'npx @astryxdesign/cli'],
    ['pnpm-lock.yaml', '', 'pnpm dlx @astryxdesign/cli'],
    ['yarn.lock', YARN_BERRY_LOCK, 'yarn dlx @astryxdesign/cli'],
    ['yarn.lock', YARN_V1_LOCK, 'npx @astryxdesign/cli'],
    ['bun.lockb', '', 'bunx @astryxdesign/cli'],
  ])(
    'prints the scoped package for a project with no local CLI (%s), launched from an installed path',
    (lockfile, contents, expected) => {
      process.argv[1] = INSTALLED_ENTRY;
      const dir = makeTmpDir();
      fs.writeFileSync(path.join(dir, lockfile), contents);
      expect(isCliOneOff()).toBe(false);
      expect(getCliInvocation(dir)).toBe(expected);
    },
  );

  it('prints the scoped package for a fresh package with no lockfile or install', () => {
    process.argv[1] = INSTALLED_ENTRY;
    const dir = makeTmpDir();
    delete process.env.npm_config_user_agent;
    fs.writeFileSync(path.join(dir, 'package.json'), '{"name":"fresh"}');
    expect(getCliInvocation(dir)).toBe('npx @astryxdesign/cli');
  });

  it('uses the dlx runner + scoped package when run one-off', () => {
    process.argv[1] = '/home/u/.npm/_npx/a1b2/node_modules/.bin/astryx';
    const dir = makeTmpDir();
    delete process.env.npm_config_user_agent;
    expect(getCliInvocation(dir)).toBe('npx @astryxdesign/cli');
  });

  it('pairs the dlx runner with the scoped package for pnpm one-off', () => {
    process.argv[1] = '/home/u/.cache/pnpm/dlx/9f/node_modules/@astryxdesign/cli/bin/astryx.mjs';
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    expect(getCliInvocation(dir)).toBe('pnpm dlx @astryxdesign/cli');
  });
});

describe('formatCliCommand', () => {
  it('strips a leading "astryx" token and prepends the invocation stem', () => {
    process.argv[1] = '/proj/node_modules/@astryxdesign/cli/bin/astryx.mjs';
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
    linkCliBin(dir);
    expect(formatCliCommand('astryx component Button', dir)).toBe('pnpm exec astryx component Button');
  });

  it('accepts a bare subcommand (no leading astryx)', () => {
    process.argv[1] = '/proj/node_modules/@astryxdesign/cli/bin/astryx.mjs';
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'package-lock.json'), '{}');
    linkCliBin(dir);
    expect(formatCliCommand('docs tokens', dir)).toBe('npx astryx docs tokens');
  });

  it('rewrites to the scoped package for one-off invocations', () => {
    process.argv[1] = '/home/u/.npm/_npx/a1b2/node_modules/.bin/astryx';
    const dir = makeTmpDir();
    fs.writeFileSync(path.join(dir, 'package-lock.json'), '{}');
    expect(formatCliCommand('astryx component Button', dir)).toBe('npx @astryxdesign/cli component Button');
  });
});
